name: Epic Brickworks Join Bot

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run bot
        env:
          GROUP_ID: ${{ secrets.GROUP_ID }}
          ROLE_3L: ${{ secrets.ROLE_3L }}
          ROLE_4L: ${{ secrets.ROLE_4L }}
          ROLE_5L: ${{ secrets.ROLE_5L }}
          ROLE_VERIFIED: ${{ secrets.ROLE_VERIFIED }}
          ROBLOX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
        run: node bot.js
